### ISSUE TITLE
xud container exec_run "getinfo -j" triggers docker.errors.APIError 409 Conflict

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#291] opened 2020-02-12 18:35 UTC
```
➜  ~ bash xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
/home/ar/.xud-docker/mainnet does not exist, would you like to create this directory? [Y/n] Y

🌍 Checking for updates ...
Failed to check for image updates. Try again? [Y/n] Y
* Image exchangeunion/xud:1.0.0-beta: outdated
* Image exchangeunion/raiden:latest: outdated
* Image exchangeunion/geth:1.9.9: outdated
* Image exchangeunion/bitcoind:0.19.0.1: outdated
* Container mainnet_bitcoind_1: missing
* Container mainnet_litecoind_1: missing
* Container mainnet_geth_1: missing
* Container mainnet_lndbtc_1: missing
* Container mainnet_lndltc_1: missing
* Container mainnet_raiden_1: missing
* Container mainnet_xud_1: missing
Pulling exchangeunion/xud:1.0.0-beta
Pulling exchangeunion/raiden:latest
Pulling exchangeunion/geth:1.9.9
Pulling exchangeunion/bitcoind:0.19.0.1
Creating mainnet_bitcoind_1
Creating mainnet_litecoind_1
Creating mainnet_geth_1
Creating mainnet_lndbtc_1
Creating mainnet_lndltc_1
Creating mainnet_raiden_1
Creating mainnet_xud_1
❌ Failed to launch mainnet environment. For more details, see /home/ar/.xud-docker/mainnet/mainnet.log
```

[mainnet.log](https://github.com/ExchangeUnion/xud-docker/files/4194264/mainnet.log)

**Comment by erkarl** [comment] 2020-02-12 18:39
Another similar attempt (slightly different logs):
```
➜  ~ bash xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
/home/ar/.xud-docker/mainnet does not exist, would you like to create this directory? [Y/n] Y

🌍 Checking for updates ...
* Container mainnet_xud_1: outdated
A new version is available. Would you like to upgrade (Warning: this may restart your environment and cancel all open orders)? [Y/n] Y
Recreating mainnet_xud_1
❌ Failed to launch mainnet environment. For more details, see /home/ar/.xud-docker/mainnet/mainnet.log
```

[mainnet.log](https://github.com/ExchangeUnion/xud-docker/files/4194292/mainnet.log)

**Comment by kilrau** [comment] 2020-02-14 18:34
ARM64: on master pulling correct ARM images for all *but* `bitcoind` & `xud`:
```
mainnet > status
┌───────────┬────────────────────────────────────────────────┐
│ SERVICE   │ STATUS                                         │
├───────────┼────────────────────────────────────────────────┤
│ bitcoind  │ Container exited                               │
├───────────┼────────────────────────────────────────────────┤
│ litecoind │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ geth      │ Ready (Connected to external)                  │
├───────────┼────────────────────────────────────────────────┤
│ lndbtc    │ Wallet locked. Unlock with xucli unlock.       │
├───────────┼────────────────────────────────────────────────┤
│ lndltc    │ Wallet locked. Unlock with xucli unlock.       │
├───────────┼────────────────────────────────────────────────┤
│ raiden    │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
│ xud       │ Container exited                               │
└───────────┴────────────────────────────────────────────────┘
```

**Comment by kilrau** [comment] 2020-02-14 19:01
AMD64: on master all images are pulled correctly
```
> status
┌───────────┬────────────────────────────────────────────────┐
│ SERVICE   │ STATUS                                         │
├───────────┼────────────────────────────────────────────────┤
│ bitcoind  │ Syncing 0.00% (0/34000)                        │
├───────────┼────────────────────────────────────────────────┤
│ litecoind │ Loading block index...                         │
├───────────┼────────────────────────────────────────────────┤
│ geth      │ Waiting for sync                               │
├───────────┼────────────────────────────────────────────────┤
│ lndbtc    │ Wallet locked. Unlock with xucli unlock.       │
├───────────┼────────────────────────────────────────────────┤
│ lndltc    │ Wallet locked. Unlock with xucli unlock.       │
├───────────┼────────────────────────────────────────────────┤
│ raiden    │ Waiting for sync                               │
├───────────┼────────────────────────────────────────────────┤
│ xud       │ failed to fetch status                         │
└───────────┴────────────────────────────────────────────────┘

**Comment by kilrau** [comment] 2020-06-19 17:15
Found the root cause for this? @reliveyy

**Comment by kilrau** [comment] 2020-07-08 10:58
Closing this, since we haven't seen this in a while.

**Closed by kilrau** 2020-07-08 10:58 UTC
Labels: P3, bug
