### ISSUE TITLE
Testnet | Not able to connect manually

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#284] opened 2020-01-31 10:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kilrau** [comment] 2020-01-31 11:15
Duplicate of https://github.com/ExchangeUnion/xud-docker/issues/105

**Closed by kilrau** 2020-01-31 11:15 UTC
