### ISSUE TITLE
Report "Branch ... does not exist" when meeting network failure

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#220] opened 2019-10-28 20:38 UTC
This error message is misleading and should report the network failure instead.

**Comment by kilrau** [comment] 2020-01-14 12:36
I couldn't reproduce this on current master. Error message looks fine to me:
```
kilrau@K-Yoga:~$ xud
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
🌍 Checking for updates ...
Failed to check for image updates. Try again? [Y/n] 
```

Closing. Please reopen if it's a different scenario you are describing @reliveyy

**Closed by kilrau** 2020-01-14 12:36 UTC
Labels: P3, bug
