### ISSUE TITLE
Unable to enter xud.sh environment when the environment is already running

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#292] opened 2020-02-14 14:45 UTC
```
xud@xud1-testnet:~$ bash xud.sh -b expose-xud-grpc
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 2
🚀 Launching testnet environment
docker: Error response from daemon: Conflict. The container name "/testnet_utils" is already in use by container "b242553b17990e3b3a396bdf022920a1a421bfd9e60e2d9644f3277842cae82d". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**Comment by kilrau** [comment] 2020-02-14 14:49
Duplicate of https://github.com/ExchangeUnion/xud-docker/issues/260

**Closed by kilrau** 2020-02-14 14:49 UTC
Labels: bug
