### ISSUE TITLE
Switch to native bash inside utils

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#293] opened 2020-02-14 19:02 UTC
I'm unable to paste my clipboard to the xud.sh environment. This makes connecting to other nodes extremely cumbersome.

**Comment by kilrau** [comment] 2020-02-14 19:06
Can confirm this.

**Comment by reliveyy** [comment] 2020-02-14 21:56
It is becuase current xudctl is a very simple shell written in python. We should use bash instead otherwise we need to figure out how to implement console copy-paste in python.

**Comment by kilrau** [comment] 2020-02-14 22:04
Why can't it just be a regular bash running inside the utils container...?

**Comment by reliveyy** [comment] 2020-02-21 11:11
> Why can't it just be a regular bash running inside the utils container...?

Yes. We could run bash insde utils.

**Comment by kilrau** [comment] 2020-02-21 11:24
That sounds like the best and easiest option to me.

Any downsides?

**Comment by reliveyy** [comment] 2020-02-21 12:06
> Any downsides?

@kilrau The best solution is using outside bash with utils container as a toolbox. So we will not need to map "/" into containers.

**Comment by kilrau** [comment] 2020-02-21 13:54
But that again introduces bash issues (different versions on different linux distros and especially macOS). Apart from the downside that we have to map / into the container - anything else?

**Comment by reliveyy** [comment] 2020-02-21 17:07
> Apart from the downside that we have to map / into the container - anything else?

### Inside bash

Pros:
- Platform independent
- Could use more python

Cons:
- Need to map "/" into the utils container
- Need to keep utils running
- Cannot sudo chown
- Slower (need to start a container)

### Outside bash

Pros:
- No need to map "/" into the utils container
- No need to run utils all the time
- Could sudo chown
- Faster

Cons:
- Platform dependent (bash versions compatibility issue. In order to run on all platforms we should stick to bash 3 features)
- Bash programming is painful

**Comment by kilrau** [comment] 2020-02-24 08:30
Great Pro/Con list! @reliveyy 

Your opinion? @erkarl

**Comment by erkarl** [comment] 2020-02-25 12:03
I'm leaning towards inside bash to avoid compatibility issues IF we can make it work and have basic functionality such as copy paste and autocomplete. I do see us ultimately having UI layer on top of it for novice users.

For advanced users/tasks we can direct them to directly ssh into the containers for full control.

**Comment by reliveyy** [comment] 2020-02-26 10:02
@erkarl @kilrau My ideal design of xud-docker UI initially comes like we integrate into current user's shell (bash, zsh or something else). This is like Python virtualenv, NodeJS nvm, Ruby bundler. But what makes it different is that we do not want to leak "dependencies". And these dependencies are very necessary when you programming more and more complicated logic. So we have bash-utils hybrid design now. Currently most functionalities are in utils.

Since I have fixed copy-paste in the restore PR https://github.com/ExchangeUnion/xud-docker/pull/287/commits/8d02a0a33d3b83176ea362eee9d99e1c4786e675 by decoding input bytes sequentially, this issue it not that urgent anymore.

And for novice users, I still believe a graphic user interface is much better than current command-line user interface.

**Comment by hatmer** [comment] 2020-06-02 06:47
Based on the discussion, i.e. that the existing shell now supports copy-paste, this issue is now a duplicate of #254

**Closed by hatmer** 2020-06-02 06:47 UTC
Labels: P3, enhancement
