### ISSUE TITLE
Use dockerhub to build images automatically

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#17] opened 2019-06-10 11:33 UTC
* simnet/testnet: auto-update to latest master
* mainnet: auto-update to latest release

**Comment by kilrau** [comment] 2019-09-04 09:22
In my opinion the only way to be fully transparent and for users to be sure that they are running the code from github is to build images locally directly from the github repos. Exception is Simnet, where the build is based on the native simnet scripts and takes very long. No need to be transparent for Simnet.

In summary my suggestion is:
* simnet: auto-update to latest master, push images to dockerhub.
* testnet: adjust update to check github for latest master. Build images locally directly from github. Main Purpose: test if local build+update works before tagging a release.
* mainnet: adjust update to check github for release tag. Build images locally directly from github.

Let me know what you think. Also @erkarl @michael1011

**Comment by michael1011** [comment] 2019-09-04 09:52
@kilrau are you talking about all images or just the XUD one?

**Comment by kilrau** [comment] 2019-09-04 10:30
Above only for `xud`.

But good point, how should we handle L2 and L3 client images?

**Comment by michael1011** [comment] 2019-09-04 10:42
Right now we are building everything from source which takes forever and a day. Therefore I don't thinks it's viable to let the users build the images themselves. And using the binaries of official releases is not option for LND because we need the `invoicesrpc` build tag. I would leave the everything as is and provide all images via Docker Hub but point out in the documentation how the images can be built.

**Comment by kilrau** [comment] 2019-10-08 11:32
Agreed.

**Comment by kilrau** [comment] 2019-10-08 11:33
Since we spent quite some time asking for and building/pushing for "latest" image, I'd say this is pretty important. Let's do it in this cycle for `1.0.0-beta`!

**Comment by kilrau** [comment] 2019-10-08 13:28
Duplicate of https://github.com/ExchangeUnion/xud-docker/issues/132, closing.

**Closed by kilrau** 2019-10-08 13:28 UTC
Labels: P2, enhancement
